import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export interface LocationImage {
  url: string
  alt: string
}

export interface Location {
  id: string
  name: string
  description: string
  images: LocationImage[]
  audioUrl: string
  transcript: string
  coordinates: {
    lat: number
    lng: number
  }
}

export const useLocationsStore = defineStore('locations', () => {
  const locations = ref<Location[]>([
    {
      id: 'main-street-depot',
      name: 'Main Street Depot',
      description: 'Historic railway station from 1882',
      images: [
        { url: 'https://picsum.photos/800/600?random=1', alt: 'Main Street Depot exterior' },
        { url: 'https://picsum.photos/800/600?random=2', alt: 'Depot interior' },
        { url: 'https://picsum.photos/800/600?random=3', alt: 'Historical photo' }
      ],
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      transcript: `Welcome to the Main Street Depot, a cornerstone of Trinidad's rich history. Built in 1882, this magnificent structure served as the gateway to the American West for countless pioneers and travelers.

The depot's architecture reflects the Victorian era's grandeur, with its distinctive red brick facade and ornate wooden trim. As trains rolled in daily, bringing goods, mail, and new residents, the depot became the beating heart of our community.

In its heyday, you could hear the whistle of steam locomotives echoing through the valley, announcing arrivals and departures. Families gathered here to greet loved ones, merchants received their goods, and stories from distant places filled the air.

Today, the depot stands as a testament to Trinidad's enduring spirit and its crucial role in America's westward expansion.`,
      coordinates: { lat: 37.1694, lng: -104.5058 }
    },
    {
      id: 'mitchell-museum',
      name: 'A.R. Mitchell Museum',
      description: 'Western and Hispanic art collection',
      images: [
        { url: 'https://picsum.photos/800/600?random=4', alt: 'Museum exterior' },
        { url: 'https://picsum.photos/800/600?random=5', alt: 'Gallery interior' }
      ],
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
      transcript: `The A.R. Mitchell Museum of Western Art houses one of the finest collections of Western and Hispanic art in the region. Arthur Roy Mitchell, a prolific artist and illustrator, created over 160 magazine covers and countless illustrations that defined the visual landscape of the American West in the early 20th century.

Mitchell's work captures the romance and reality of frontier life, from cowboys and Native Americans to the stunning landscapes of Colorado. His attention to detail and authentic portrayal of Western life made him one of the most respected Western artists of his time.

The museum also features works by other notable Western artists and preserves the cultural heritage of Trinidad's Hispanic community through its extensive collection of santos and retablos.`,
      coordinates: { lat: 37.1697, lng: -104.5061 }
    },
    {
      id: 'historic-downtown',
      name: 'Historic Downtown',
      description: 'Victorian-era commercial district',
      images: [
        { url: 'https://picsum.photos/800/600?random=6', alt: 'Downtown street view' }
      ],
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      transcript: `Trinidad's Historic Downtown district is a living museum of Victorian and early 20th-century architecture. Walking these streets is like stepping back in time, where ornate facades and period details tell the story of a thriving frontier town.

Many of these buildings housed saloons, mercantiles, and hotels during the coal mining boom. The wealth generated by coal is reflected in the elaborate architecture you see today.`,
      coordinates: { lat: 37.1691, lng: -104.5055 }
    }
  ])

  const currentLocation = ref<Location | null>(null)

  function setCurrentLocation(locationId: string) {
    currentLocation.value = locations.value.find(loc => loc.id === locationId) || null
  }

  function getNearbyLocations(locationId: string, maxDistance: number = 10) {
    const current = locations.value.find(loc => loc.id === locationId)
    if (!current) return []

    // Calculate distance using Haversine formula
    const calculateDistance = (lat1: number, lng1: number, lat2: number, lng2: number): number => {
      const R = 6371 // Earth's radius in km
      const dLat = toRad(lat2 - lat1)
      const dLng = toRad(lng2 - lng1)
      const a =
        Math.sin(dLat / 2) * Math.sin(dLat / 2) +
        Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) * Math.sin(dLng / 2)
      const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
      return R * c
    }

    const toRad = (degrees: number) => degrees * (Math.PI / 180)

    return locations.value
      .filter(loc => loc.id !== locationId)
      .map(loc => ({
        ...loc,
        distance: calculateDistance(
          current.coordinates.lat,
          current.coordinates.lng,
          loc.coordinates.lat,
          loc.coordinates.lng
        )
      }))
      .filter(loc => loc.distance <= maxDistance)
      .sort((a, b) => a.distance - b.distance)
  }

  return {
    locations,
    currentLocation,
    setCurrentLocation,
    getNearbyLocations
  }
})
